### ISSUE TITLE
Error when running it on x86_64 ubuntu machine

### ISSUE THREAD

**Issue by geliAI** [CovMat/GMT-mini-GUI#2]
Hi,
I tried to run compiled version on an x86_64 ubuntu machine, but has this problem during the attempt:
XXX@gofar:~/Downloads/GMTGUI-LIBS$ ls
ls: relocation error: libc.so.6: symbol _dl_starting_up version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference.
Not working either when adding to the path in .bash.sr.

**Comment by CovMat** [comment]
It seems that your Ubuntu system has been broken...

Can you use "ls" normally?

please check:
https://www.jianshu.com/p/5ea4e50bf800
https://blog.csdn.net/lpf63126528/article/details/76188573

**Comment by CovMat** [comment]
sorry it is my problem. I have update the code.
